### ISSUE TITLE
Generic WebSocket module

### ISSUE THREAD

**Issue by krzyc** [bitfocus/companion-module-generic-websocket#1]
Device: Generic WebSocket software (or hardware)
Goal: Control software with small userbase (mostly proprietary, sometimes custom-written for 1 user) which often supports WS control.

I saw, that this is against your project principles, but I also saw that some users are interested in introducing Generic WebSocket module. I have written one to control dedicated software - 1 user, so introducing dedicated module will not add additional value to Companion and generate high costs.

Please, take into account, that there are many solutions like this and some power-users can benefit from this module to speed up deployment.

My module allows one to send any command by WebSocket connection.

If my arguments convince you, please create companion-module-generic-ws repo so I can make a PR. If you have any suggestions besides included in "Module Development" doc, please submit them and I will try to include it in my code before submitting.

Thanks for a great job with Companion.

**Comment by ruudboon** [comment]
Any news on this?

**Comment by gohamstergo** [comment]
@krzyc any update?

**Comment by krzyc** [comment]
@josephdadams @gohamstergo I have no write access to this repository so I created a pull request #2. Sorry for a delay.

**Comment by josephdadams** [comment]
@krzyc thanks. I gave you push access to the repo awhile back but it still says pending invite. We will review the PR and get back

**Comment by krzyc** [comment]
@josephdadams I have missed your invitation sent on 2020-08-20 and it expired after 7 days. Thanks.

**Comment by krocheck** [comment]
let's try that again then @krzyc

**Comment by krzyc** [comment]
@krocheck Works, thanks. Should I merge PR now or wait for your review?

**Comment by krocheck** [comment]
Its easier for us if you PR release/updates but with your access manage the tickets ... so yeah, we'll review as it is.

**Comment by krzyc** [comment]
@krocheck Thanks for suggestions, I have updated my PR. What should I do next? Do you think my PR is ready for merge now?

I wonder whether I should add some kind of reconnect timer. Do you have any recommendations? Should it be hard-coded or user configurable?

**Comment by krzyc** [comment]
@josephdadams @krocheck Hey, what do you think about my PR? Do you have any suggestions?

**Comment by gohamstergo** [comment]
@josephdadams @krocheck just checking in :)

**Comment by Knut-Knoblauch** [comment]
Proprietary software being controlled by just one user is very limited.  There are a lot of hurdles here.  Firstly the software could be running when the module connects in.  The software state must be communicated down to the plugin.  Secondly, the software shouldn't be able to be automatically taken over by a plugin.  Malicious users could step in and be disruptive.  The software needs to be able to do things to be controlled.  It needs to be in remote control mode and also it needs to grant remote control access to the connection.  Have you considered all these things?  Before just creating a plugin I would like to see some public discourse of a protocol.  FWIW - I think using the Mosquitto MQTT protocol is a richer solution.  In that case, the software being controlled and the plugin will use the Mosquitto server as a broker.

**Comment by JeffreyDavidsz** [comment]
@Knut-Knoblauch I don't really see/understand the point you are making. Initially we where against generic-modules. As it would not help others which the same challenges. Using a simple WS module would give some users the possibility to control devices which accept websockets

**Comment by Julusian** [comment]
As this module now exists, it doesnt look like this issue is needed any more
