### ISSUE TITLE
Filename parameter

### ISSUE THREAD

**Issue by nick-potts** [bitfocus/companion-module-generic-websocket#10]
The websocket I need to connect to is ws://127.0.0.1:8888/ws

There's no way to specify '/ws' and so I can't connect. I realize its unconventional, but I can't modify the server application.

**Comment by krzyc** [comment]
Good point. Maybe we should drop host and port configuration for URL field? This will allow entering full URL like:
ws[s]://domain[:port][/path]

**Comment by rihani** [comment]
any idea how to send the following please  `ws://192.168.1.99/mqtt`  topic: `Session/0/Stream/0/unpublish/0` data: `{"unpublish":"unpublish"}`
