### ISSUE TITLE
Need to send HEX - no string!

### ISSUE THREAD

**Issue by Stoeff-chen** [bitfocus/companion-module-generic-websocket#16]
Hey there - I try my best to use this module but I cannot. I guess my pure hex code has to be transformed but in my case this is not possible. With wireshark I see that the sent message adds always the carrier return. 

What can I do?

**Comment by krzyc** [comment]
Hi, in current version \r\n is forced by plugin.
`this.ws.send(value + '\r\n')`
Preferred solution would be to add an opt-out option for this.

**Comment by Stoeff-chen** [comment]
This would be so cool if I could just send the hex code without anything :)
