### ISSUE TITLE
Error 1006 with Cantabile Websocket

### ISSUE THREAD

**Issue by mmf431** [bitfocus/companion-module-generic-websocket#21]
I unfortunately cannot connect to Cantabile's websocket ws://localhost:35007/api/socket. 

Error in log reads: Instance/Wrapper/websocket: WebSocket error: Error: Unexpected server response: 301
And in status it says: Connection closed with code 1006

With Postman the connection to the above websocket URI is readily established.

Here is the description of Cantabile's Websocket:
https://www.cantabilesoftware.com/netapi/

I would be very happy to connect to Cantabile (which is a great program) via Companion's websocket module.

**Comment by istnv** [comment]
Response 301 is a redirect. The server knows what you are asking, but there is a better address.
Check your address for a '/' at the end. Try with and without the trailing '/'.

**Comment by mmf431** [comment]
Hey, great! I added a trailing slash to the websocket URI and now the module connects. You saved my day! Thank you very much.
