### ISSUE TITLE
Variable not being passed to data in generic websocket module

### ISSUE THREAD

**Issue by br1an-c0des** [bitfocus/companion-module-generic-websocket#4]
Hello!

The module has been working great for me, except that it seems the module is not parsing/passing internal variables into the "data".

I took a Wireshark capture of the packet, and the data just comes out as what I input for the variable.
<img width="958" alt="websocket variable 1" src="https://user-images.githubusercontent.com/9284920/162761081-f53964e5-7de2-4729-8a34-dc13e1fcae95.png">

If anyone is able to take a look, hopefully it's a simple fix.  Thanks!

**Comment by krzyc** [comment]
Hi,
thanks for a report. I think this feature is very useful - PR is awaiting review.
