### ISSUE TITLE
Reconnect not paying attention to Disable/Enable in Connections.

### ISSUE THREAD

**Issue by nbdevito** [bitfocus/companion-module-generic-websocket#8]
With Reconnect enabled, using the disable button in connections (especially in debugging and programming against), it seems the reconnection loop is not properly closed out and after 5 seconds it reconnects.  

Re-enabling creates another connection to my Websocket and I can quickly have multiple connections from the same Companion instance.

**Comment by krzyc** [comment]
Thanks for feedback, PR is awaiting - it fixes registering timer twice (on error and on close) and now timer will be correctly destroyed on destroy.
